### ISSUE TITLE
please update postgraphile-plugin-connection-filter dependency

### ISSUE THREAD

**Issue by barbalex** [graphile-contrib/postgraphile-plugin-connection-filter-postgis#13]
After updating postgraphile-plugin-connection-filter to v2.0.0 I get this error when starting postgraphile:

```bash
root@pca:/mnt/c/Users/alexa/apf2# DEBUG="graphile-build:warn" npx postgraphile   --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related,@graphile/postgis,postgraphile-plugin-connection-filter-postgis    --jwt-token-identifier auth.jwt_token   --default-role postgres   --jwt-secret secret   -c postgres://postgres:secret@localhost:5432/apflora   -s apflora   --cors   --enable-query-batching   --enhance-graphiql   --watch   --export-schema-json schema.json

PostGraphile v4.7.0 server listening on port 5000 �

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql
  ‣ Postgres connection: postgres://postgres:[SECRET]@localhost/apflora (watching)
  ‣ Postgres schema(s):  apflora
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Join Joe Dennis in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: Plugin postgraphile-plugin-connection-filter-postgis@1.0.0-alpha.5 requires postgraphile-plugin-connection-filter@^1.0.0 (current version: 2.0.0)
    at depends (/mnt/c/Users/alexa/apf2/node_modules/postgraphile-plugin-connection-filter-postgis/index.js:22:15)
    at PostGraphileConnectionFilterPostgisPlugin/build/unnamed (/mnt/c/Users/alexa/apf2/node_modules/postgraphile-plugin-connection-filter-postgis/index.js:32:5)
    at SchemaBuilder.applyHooks (/mnt/c/Users/alexa/apf2/node_modules/graphile-build/node8plus/SchemaBuilder.js:252:20)
    at SchemaBuilder.createBuild (/mnt/c/Users/alexa/apf2/node_modules/graphile-build/node8plus/SchemaBuilder.js:307:24)
    at SchemaBuilder.buildSchema (/mnt/c/Users/alexa/apf2/node_modules/graphile-build/node8plus/SchemaBuilder.js:321:26)
    at SchemaBuilder.watchSchema (/mnt/c/Users/alexa/apf2/node_modules/graphile-build/node8plus/SchemaBuilder.js:386:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.watchPostGraphileSchema (/mnt/c/Users/alexa/apf2/node_modules/postgraphile-core/node8plus/index.js:252:5)
    at async createGqlSchema (/mnt/c/Users/alexa/apf2/node_modules/postgraphile/build/postgraphile/postgraphile.js:67:21)
```

**Comment by mattbretl** [comment]
I just published 1.0.0-alpha.6 with the fix.
